### ISSUE TITLE
私聊的接口无法使用

### ISSUE THREAD

**Issue by xiaobaozi233** [ssttkkl/BangumiBot#2]
HTTP:500
![图片](https://user-images.githubusercontent.com/68990805/91627120-a436e680-e9e7-11ea-80a6-3c1021ecbdbc.png)

**Comment by ssttkkl** [comment]
这个应该是目前mirai-api-http（我看gomirai的源码实现方式应该没问题）还不能向好友发送长消息的问题，暂时无能为力

**Comment by ssttkkl** [comment]
现在通过分割私聊消息解决了
